
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://root:0530@localhost:3306/proddb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #password: 0530 #change this to your database username
    #username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect